### ISSUE TITLE
Arrow entity crashes server

### ISSUE THREAD

**Issue by DeadlyShyKitten** [TunefulTurnip/Deep-Aether#137]
im pretty sure this is a deep ather issue as it only fixes if i remove deep ather but something shoots an arrow (dont know what kind) at us and the server crashes. I dont think its a normal arrow as skeletons had been shooting  me for hours just fine.
[crash-2024-01-09_01.53.27-server.txt](https://github.com/RazorDevs/Deep-Aether/files/13869632/crash-2024-01-09_01.53.27-server.txt)

**Comment by darksonic300** [comment]
This is fixed in the latest hotfix version.

**Comment by DeadlyShyKitten** [comment]
> This is fixed in the latest hotfix version.

Apologies but I did the update of jan 2nd on curse forge and the issue still persisted.. Where would this hotfix update be?
![image](https://github.com/RazorDevs/Deep-Aether/assets/156054043/e600f6c5-f409-48be-8e39-273b94b3857f)

**Comment by TunefulTurnip** [comment]
Have you also updated the server to the latest version of Deep Aether?  The log says you're using version 1.0.13 of Deep Aether instead of 1.0.13.1.

**Comment by DeadlyShyKitten** [comment]
> Have you also updated the server to the latest version of Deep Aether? The log says you're using version 1.0.13 of Deep Aether instead of 1.0.13.1.

ill try that again but yes I had done that. Maybe the FTP bugged again.. thank you so much!
